DROP TABLE IF EXISTS users, users_subscriptions, subscriptions;

CREATE TABLE IF NOT EXISTS users (
     user_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     user_name	              VARCHAR(255) NOT NULL,
     user_email               VARCHAR(255) UNIQUE NOT NULL
     );

CREATE TABLE IF NOT EXISTS subscriptions (
     subscription_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     subscription_name	      VARCHAR(255) UNIQUE NOT NULL
     );

CREATE TABLE IF NOT EXISTS users_subscriptions (
     user_id                  BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
     subscription_id          BIGINT REFERENCES subscriptions (subscription_id) ON DELETE CASCADE,
     CONSTRAINT PK_USERS_SUBSCRIPTIONS PRIMARY KEY(user_id, subscription_id)
     );